export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    AUCTIONS: "/auctions",
    AUCTION_DETAILS: (id: string) => `/auctions/${id}`,
    ABOUT: "/about",
    CONTACT: "/contact",
  },
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    REGISTER_PAYMENT: "/register/payment",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  USER: {
    DASHBOARD: "/user/dashboard",
    AUCTIONS: "/user/auctions",
    AUCTION_DETAILS: (id: string) => `/user/auctions/${id}`,
    OFFERS: "/user/offers",
    WATCHLIST: "/user/watchlist",
    PURCHASES: "/user/purchases",
    NOTIFICATIONS: "/user/notifications",
    PROFILE: "/user/profile",
    SETTINGS: "/user/settings",
    LIVE_ROOM: (id: string) => `/user/live/${id}`,
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    AUCTIONS: "/admin/auctions",
    CREATE_AUCTION: "/admin/auctions/create",
    AUCTION_DETAILS: (id: string) => `/admin/auctions/${id}`,
    EDIT_AUCTION: (id: string) => `/admin/auctions/${id}/edit`,
    VEHICLES: "/admin/vehicles",
    USERS: "/admin/users",
    OFFERS: "/admin/offers",
    REPORTS: "/admin/reports",
    SETTINGS: "/admin/settings",
  },
} as const;
